<?php


$category = array(
 'BERLINE'=>array(
            "Honda Accord",
            "<img src=\"images/accord.jpg\" alt =\"photo\"></a>",
            "140.000km",
            "2014",
            "20900$",
            "mercedes E220",
            "<img src=\"images/c203.jpg\" alt =\"photo\"></a>",
            "100.000km",
            "2010",
            "19900$",
            "toyota corola",
            "<img src=\"images/corola.jpg\" alt =\"photo\"></a>",
            "100.000km",
            "2010",
            "19900$",
            "hyunday elentra",
            "<img src=\"images/elentra.jpg\" alt =\"photo\"></a>",
            "100.000km",
            "2008",
            "9900$",
            "kia forte",
            "<img src=\"images/forte.jpg\" alt =\"photo\"></a>",
            "101.000km",
            "2013",
            "23900$"
    ),
  'HATCHBACK'=> array(
            "Honda civic",
            "<img src=\"images/civic.jpg\" alt =\"photo\"></a>",
            '115.000km',
            '2011',
            '10900$',
            "Mercedes class a",
            "<img src=\"images/classa.jpg\" alt =\"photo\"></a>",
            '125.000km',
            '2013',
            '24900$',
            "Toyota auris",
            "<img src=\"images/auris.jpg\" alt =\"photo\"></a>",
            '140.000km',
            '2009',
            '10900$',
            "Hyunday accent",
            "<img src=\"images/accent.jpg\" alt =\"photo\"></a>",
            '118.000km',
            '2008',
            '7400$',
            " Kia rio",
            "<img src=\"images/rio.jpg\" alt =\"photo\"></a>",
            '112.000km',
            '2008',
            '6900$',
    ),
  'SUV'  =>  array(
            "Honda crv",
            "<img src=\"images/crv.jpg\" alt =\"photo\"></a>",
            '135.000km',
            '2013',
            '13900$',
            "Mercedes glk",
            "<img src=\"images/glk.jpg\" alt =\"photo\"></a>",
            '125.000km',
            '2015',
            '29900$',
            "Toyota rav4",
            "<img src=\"images/rav4.jpg\" alt =\"photo\"></a>",
            '160.000km',
            '2009',
            '14900$',
            "Hyunday tucson",
            "<img src=\"images/tucson.jpg\" alt =\"photo\"></a>",
            '110.000km',
            '2012',
            '11900$',
            "kia sol",
            "<img src=\"images/soul.jpg\" alt =\"photo\"></a>",
            '119.000km',
            '2011',
            '11900$',
        )
    );
